cart/urls.py
from django.conf.urls import url

from . import views

app_name = "cart"

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

rungmuacafe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),
    path('shop/', include('shop.urls')),
    path('', include('main.urls')),
]

shop/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'shop'

urlpatterns = [
    path('products', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),

]

shop/models.py
from django.db import models
from django.urls import reverse  # generate urls from url patterns


# Create your models here.



class Category (models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Enter a product category (e.g. Coffee Bean, Drink, Cake, Souvenir etc.)"
    )
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

    name = models.CharField(max_length=200, db_index=True, unique=True)
    image = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField(default=10)
    available = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def checkavailability (self):
        if self.stock ==0:
            self.available = False

        return self.available

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/product_list.html', context)

shop/templates/shop/product/product_list.html
{% extends "base_generic.html" %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Online Shopping Products {% endif %}
{% endblock %}

{% load staticfiles %}
{% block content %}
    <!-- Container (Portfolio Section) -->
<main class="w3-content w3-container w3-padding-64">
    <h3 class="w3-center"> {% if not category %} All Products {% else %} {{ category.name }} {% endif %} </h3>
    <p class="w3-center"><em> Click on the images to make them bigger</em></p><br>

    <!-- Responsive Grid. Four columns on tablets, laptops and desktops. Will stack on mobile devices/small screens (100% width) -->
    <div class="w3-row-padding w3-center">
        {% for product in products %}

        <div class="w3-col m4">

            <img src="/static/img/{{ product.image }}" alt="{{ product.name }}" style="height:120px" data-toggle="modal"
                 data-target="#{{ product.name }}"
                 class="w3-hover-opacity">
            <div class="modal fade" id="{{ product.name }}">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h6 class="modal-title">{{ product.name }}</h6>
                            <button type="button" class="close" data-dismiss="modal">×</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            <p class="text-center">{{ product.description }}</p>
                            <p class="text-center">{{ product.price }}</p>
                            <br>
                            <img src="{{ product.image }}"
                                 style='height: 100%; width: 100%; object-fit: contain'/>
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>

            <div class="caption">
                <h6 class="text-center">
                    {{ product.name }}
                </h6>
            </div>
            <p class="stock" class="text-center">Stock: {{ product.stock }}</p>
            <div class="price" alt="{{ product.price }}">
                <p class="text-center">Price: {{ product.price }}</p>
            </div>

            {% if product.stock != 0 %}
                {% if user.is_authenticated %}
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form }}

                        <button type="submit" class="btn btn-success btn-product">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Add to cart
                        </button>
                    </form>
                {% else %}
                    <button class="btn btn-success btn-product">
                        <span class="glyphicon glyphicon-shopping-cart"></span> Not Available
                    </button>
                {% endif %}

            {% else %}
            <button class="btn btn-danger btn-product" type="button" class="btn">Sold Out!</button>
            {% endif %}
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
        <div class="w3-row-padding w3-center w3-section"><br><br></div>

        <div class="w3-row-padding w3-center w3-section">

            {% endif %}
            {% endfor %}

        </div>
    </div>



<div class="modal fade" id="cartModal">
<div class="modal-dialog">
<div class="modal-content">

<!-- Modal Header -->
<div class="modal-header">
<h4 class="modal-title">Complete "Add to Cart"</h4>
<button type="button" class="close" data-dismiss="modal">×</button>
</div>

<!-- Modal body -->
<div class="modal-body">
Your purchased item has been added to Cart.
</div>

<!-- Modal footer -->
<div class="modal-footer">
<button type="button" class="btn btn-danger" data-dismiss="modal">Continue Shopping
</button>
<a href="{% url 'cart:cart_detail' %}">Go to
Cart</a>
<button type="button" class="btn" data-dismiss="modal"></button>

</div>

</div>
</div>

</div>

</main>
{% endblock %}