account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path('index/', views.index, name='index'),
]

cart/urls.py
from django.conf.urls import url

from . import views

app_name = "cart"

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutUs', views.aboutUs, name='aboutUs'),
    path('locations', views.locations, name='locations'),
    path('menu', views.menu, name='menu'),
    path('onlineShopping', views.onlineShopping, name='onlineShopping'),
    path('offers', views.offers, name='offers'),
    path('contactUs', views.contactUs, name='contactUs'),
    path('signup', views.signup, name='signup'),
    path('login', views.signin, name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

rungmuacafe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),
    path('shop/', include('shop.urls')),
    path('', include('main.urls')),
]

shop/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'shop'

urlpatterns = [
    path('products', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),

]

main/models.py
from django.db import models
from django.urls import reverse  # generate urls from url patterns
#from phone_field import PhoneField


class Feedback(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=300)
    phone_number = models.CharField(max_length=10) #PhoneField()
    feedback = models.TextField(max_length=1000)

    def __str__(self):
        return self.email

main/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

main/views.py
import csv
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

from django.shortcuts import render
from .models import Feedback
from django.http import HttpResponse


def signin(request):
    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return HttpResponse('Sign in fail, try again.')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return HttpResponse('Sign up complete')
        else:
            return HttpResponse('Sign up fail')
    else:
        form = UserForm()
        return render(request, 'addUser.html', {'form': form})


def home(request):
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {'num_visits': num_visits}
    return render(request, 'home.html', context)


def aboutUs(request):
    return render(request, 'aboutUs.html')


def locations(request):
    csv_path = 'main/static/location.csv'
    csv_file = open(csv_path, 'r')
    csv_obj = csv.DictReader(csv_file)
    csv_list = list(csv_obj)

    return render(request, 'locations.html', {'csv_list': csv_list})


def menu(request):
    return render(request, 'menu.html')


def onlineShopping(request):
    return render(request, 'onlineShopping.html')


def offers(request):
    return render(request, 'offers.html')


def contactUs(request):
    if request.method == 'POST':
        if request.POST.get('Name') and request.POST.get('Email') and request.POST.get('Phone Number') \
                and request.POST.get('Feedback'):
            post = Feedback()
            post.name = request.POST.get('Name')
            post.email = request.POST.get('Email')
            post.phone_number = request.POST.get('Phone Number')
            post.feedback = request.POST.get('Feedback')
            post.save()

            return HttpResponse("Thanks for your feedback!")

    else:
        return render(request, 'contactUs.html')

main/templates/aboutUs.html
{% extends 'base_generic.html' %}
{% block title %}About Us{% endblock %}
{% block content %}

{% load staticfiles %}

<!-- Container (Introduction Section) -->
<div class="w3-content w3-container w3-padding-64" style="text-align: justify;" id="Introduction">
  <h3 class="w3-center">Introduction</h3>
  <p class="w3-center"><em>Because...</em></p>
  <p class="w3-center"><img src="{% static 'Images/backgrounds/aboutus1.jpg' %}" style="width:70%; height:70%"></p>
  <br>
  <p>When mentioning Vietnamese specialties, Pho and Nem will be foreigners' right-off the-bat answer. But that is only one grain of salt in the whole "desert" of Viet Nam's delicious specialties. Perceiving this point, Rung Mua Cafe is willing to bring Viet Nam's traditional culture and cuisine to Korean customers, with firm belief that our selection of beverages and cakes will definitely "seduce" even our most demanding customers.
</p>
</div>


<div class="w3-row w3-center w3-light-grey w3-padding-16">
</div>


<!-- Container (Stories Section) -->
<div class="w3-content w3-container w3-padding-64" style="text-align: justify;" id="Stories">
  <h3 class="w3-center">Our stories</h3>
  <p class="w3-center"><em>Where our idea came from</em></p><br>
 <p class= "w3-center">"Rung Mua" means "Rainforest" in Vietnamese.</p>
 <p>At first, when first thinking about starting a coffee shop with special theme, the coffee shop owners - Jaeweon and Minh - were having a headache pondering which theme to choose from, in order to make our coffee shop stand out creatively, as welll as give customers the best experience. I suggested that we should go with a manga theme or a game theme, considering these are a trend in Asian countries. But then Jaeweon asked me which drinks are the most favored in Vietnam, I suddenly thought of "chè"-the most popular sweet dessert among Vietnamese high-schoolers and students. It is not a bad idea, since "Chè" is so underrated for outsiders, while I, as a "Chè" crazy fan, was very let down not being able to find a whole "chè"-specific store abroad, no matter where I went (the US, France or Korea). If boba tea can become a new worldwide tendency, why not "chè"?</p>
 <p>Since this shop will be selling Vietnamese traditional cuisine, it should have a Viet Nam themed with a Vietnamese name. So in the end, "Rung Mua" with a green and classic theme came up.</p>
 <p></p>
	<p class="w3-center"><img class= "img-fluid" class="aligncenter" src="{% static 'Images/backgrounds/aboutus2.jpg' %}"/> </p>
	<p class="w3-center"><img class= "img-fluid"  src="{% static 'Images/backgrounds/aboutus3.jpg' %}"/> </p>
	<p class="w3-center"><img class= "img-fluid"  src="{% static 'Images/backgrounds/aboutus4.jpg' %}"/> </div>


</div>

<div class="w3-row w3-center w3-light-grey w3-padding-16">
</div>

<!-- Container (Coffee Section) -->
<div class="w3-content w3-container w3-padding-64" style="text-align: justify;" id="Coffee">
  <h3 class="w3-center">Our Coffee</h3>
  <p class="w3-center"><em>Selected from Viet Nam's best source.</em></p>
<p>Coffee was introduced into Vietnam by the French in 1857. Now Viet Nam has become the second biggest coffee exporting country in the world.</p>
<p>97% of Vietnamese coffee comes from Robusta species. It is known for its low acidity and strong bitterness, thus is frequently used as instant coffee or the base for coffee mixture. Compared to Arabica, Robusta is easier to take care of, prevent diseases and have bigger crop productivity. It contains twice as much caffeine as the other coffee and more anti-oxydants. Overall, Viet Nam contributes 40% of the world's Robusta's quantity.</p>
<p>What makes Viet Nam's coffee special is that, besides having great productivity, coffee has been incorporated into Viet Nam's culture, as it appears in every Saigonese's breakfast, but also because it is consumed with Vietnamese "out-of-this-world" styles. Who would have thought that coffee could taste so good in mixture with yolk? And "cafe phin" filtered on spot will for sure leave instant coffee drinkers jawdrop. </p>
	<p class="w3-center"><img class= "img-fluid"  src="{% static 'Images/backgrounds/aboutus5.jpg' %}"></p>
    <p class="w3-center"><em>Ca phe sua da (iced milk coffee)</em></p>
	<p class="w3-center"><img class= "img-fluid"  src="{% static 'Images/backgrounds/aboutus6.jpg' %}"></p>
    <p class="w3-center"><em>Ca phe trung (egg coffee)</em></p>

</div>

{% endblock %}

main/templates/addUser.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="login">
    <h2>Sign up</h2>
    </br>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success btn-product" value="sign up" />
    </form>
</div>
{% endblock %}

main/templates/base_generic.html
<!DOCTYPE html>

{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="UTF-8">
<title>{% block title %}Rung Mua Cafe Website{% endblock %}</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Marck+Script" />
<link rel="stylesheet" href="{% static 'styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>

<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet">
<link href="https://codepen.io/elishaterada/pen/tGokD" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<style>

    .a{
        margin-top : 10px;
        margin-bottom : 10px;
        width: 100px;
    }

    .b{
        margin-top : 25px;
    }

    .c{
       margin-top : 20px;
    }

    .visit {
        margin-top: 40px;
        margin-bottom: 0px;
    }
    .login {
        margin-left: 200px;
        margin-right: 200px;
        margin-top: 100px;
        margin-bottom: 100px;
    }

    #cssmenu{
        margin-bottom:30px;
    }

    iframe{
        height:1000px;
    }

    .sold-out {
        font-size: 18px;
        color : #ff0000;
    }

    .stock {
        color : #008000;
    }

    #footer {
        padding-top: 40px;
        padding-bottom: 20px;
        padding-left:200px;
        background-color: #008000;
        height: 130px;
        position:relative;
        clear:both;
    }
    #footer p{
        color: #ffffff;

        margin-bottom: 3px;
        font-size: 11px;
        margin-left:20px;
    }
    #footer .copyright {
        position:absolute;
    }


</style>

</head>
<body>

{% if user.is_authenticated %}
 <div class="topnav">
 <a class="topnav-brand" href="{% url 'home' %}">
     <img src="{% static 'Images/backgrounds/logo.png' %}" width="40" height="40" class="d-inline-block" alt="">
    Rung Mua Café
</a>

<a href="{% url 'cart:cart_detail' %}"><i class="fa fa-fw fa-shopping-cart"></i>  Shopping Cart</a>
<a href="{% url 'account:index' %}">Account</a>
<a href="{% url 'logout' %}">Log Out</a>
<a href="#">Welcome {{ user.username }}</a>
</div>

{% else %}
<div class="topnav">
 <a class="topnav-brand" href="{% url 'home' %}">
     <img src="{% static 'Images/backgrounds/logo.png' %}" width="40" height="40" class="d-inline-block" alt="">
    Rung Mua Café
  </a>
  <a href="{% url 'login' %}"><i class="fa fa-fw fa-shopping-cart"></i>  Shopping Cart</a>

<a href="{% url 'signup' %}">Sign Up</a>
  <a href="{% url 'login' %}">Sign In</a>
  <a href="#">Welcome Customer</a>
</div>
{% endif %}


<div class="bgimg-1 w3-display-container w3-opacity-min" id="home">
	<div class="w3-display-middle">

<table id="table-logo">
    <tr><td>
        <img class= "w3-circle w3-white" src="{% static 'Images/backgrounds/logo.png' %}">
    </td></tr>
    <tr><td>
    <br>
    </td></tr>
    <tr><td>
    <span class="w3-image w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity">   RUNG <span class="w3-padding-small"> MUA </span> CAFE</span>
    </td></tr>
  </table>

</div>
</div>

<div id='cssmenu'>
    <ul>
        <li class='active'><a href="{% url 'home' %}"><span>Home</span></a></li>
        <li class='has-sub'><a href="{% url 'aboutUs' %}"><span>About Us</span></a>
            <ul>
                <li class='has-sub'><a href='#Introduction'><span>Introduction</span></a></li>
                <li class='has-sub'><a href='#Stories'><span>Our stories</span></a></li>
                <li class='has-sub'><a href='#Coffee'><span>Our Coffee</span></a></li>
            </ul>
        </li>
        <li><a href="{% url 'locations' %}"><span>Location</span></a></li>
        <li class='has-sub'><a href="{% url 'menu' %}"><span>Menu</span></a></li>
        <li class='has-sub'><a href="{% url 'shop:product_list' %}"><span>Online Shopping</span></a>
            <ul>
                <li class='has-sub'><a href="/shop/1/"><span>Coffee Beans</span></a></li>
                <li class='has-sub'><a href="/shop/2/"><span>Drinks</span></a></li>
                <li class='has-sub'><a href="/shop/3/"><span>Cakes</span></a></li>
                <li class='has-sub'><a href="/shop/4/" ><span>Souvenirs</span></a></li>
            </ul>
        </li>
        <li class='has-sub'><a href="{% url 'offers' %}"><span>Offers</span></a></li>
        <li class='has-sub'><a href="{% url 'contactUs' %}"><span>Contact Us</span></a></li>
        <li class='has-sub'><a href='#'><span></span></a></li>
    </ul>
</div>

<main>
    {% block content %}{% endblock %}


</main>


<div id="footer"><!-- footer 시작 -->
    <p>서울시 강남구 테헤란로 231</p>
    <p>대표: 이재원, Minh</p>
    <p>사업자 등록번호: 632-21-332385</p>
    <p class="copyright">Copyright ©2019 RUNGMUA All rights reserved.</p>
</div><!-- // footer 끝 -->


<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
            <h4 class="modal-title">Error</h4>
            <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
            Sign in first!
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel
            </button>
            </div>

        </div>
    </div>
</div>



</body>
</html>

main/templates/contactUs.html
{% extends 'base_generic.html' %}
{% block title %}Contact Us{% endblock %}
{% block content %}
<div class="w3-content w3-container w3-padding-64" id="contact">
  <h3 class="w3-center">CUSTOMER'S FEEDBACK</h3>
  <p class="w3-center"><em>Your feedback will be appreciated for a better service!</em></p>

  <div class="w3-row w3-padding-32 w3-section">
    <div class="w3-col m8 w3-container">
      <div class="w3-large w3-margin-bottom">

      <p>Please use the form below or contact us directly via methods on the right.</p>
      <form method="POST" name="Feedback Form"> {% csrf_token %}
        <div class="w3-large" style="margin:0 -16px 8px -16px">
        <div class="w3-half"> Customer's Name: </div>
        <div class="w3-half"><input class="w3-input w3-border" type="text" placeholder="Name" required name="Name"> </div>
        <br><br>
        <div class="w3-half"> Email: </div>
          <div class="w3-half">
            <input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">
          </div>
        <br><br>
        <div class="w3-half"> Phone Number: </div>
        <div class="w3-half"><input class="w3-input w3-border" type="tel" placeholder="Phone Number" required name="Phone Number"> </div>
        <br><br>
        <div class="w3-half"> Feedback: </div><br>
        <p>
        <textarea required name="Feedback" placeholder="Feedback" style="height:300px;" class="w3-col m12"></textarea>
        </p>
        <br><br>
        <button class="w3-button w3-black w3-right w3-section" type="submit" value="Feedback">
          <i class="fa fa-paper-plane"></i> SEND FEEDBACK
        </button>
        </div>
      </form>
      </div>
    </div>
    </div>
    <div class="w3-col m4 w3-panel">
      <div class="w3-large">
        <i class="fa fa-phone fa-fw  w3-xlarge w3-margin-right"></i> +00 151515<br>
        <i class="fa fa-envelope fa-fw  w3-xlarge w3-margin-right"></i> rungmuacafe@gmail.com<br>
        <i class="fa fa-facebook-square fa-fw  w3-xlarge w3-margin-right" style="color:#3b5998;"></i> Rung Mua Cafe<br>
        <i class="fa fa-twitter-square fa-fw  w3-xlarge w3-margin-right" style="color:#55acee;"></i> Rung Mua Cafe<br>
        <i class="fa fa-weibo fa-fw  w3-xlarge w3-margin-right" style="color:#E71D34;"></i> 雨林咖啡店<br>
        <i class="fa fa-weixin fa-fw  w3-xlarge w3-margin-right" style="color:#93d034;"></i> 雨林咖啡店<br>
    </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/home.html
{% extends 'base_generic.html' %}
{% block title %}Home{% endblock %}
{% block content %}

{% load staticfiles %}

<div class="slideshow-container">

<div class="mySlides">
  <div class="numbertext">1 / 4</div>
  <img src="{% static 'Images/backgrounds/home1.png' %}" style="width:100%" />
  <div class="text">Caption Text</div>
</div>

<div class="mySlides">
  <div class="numbertext">2 / 4</div>
  <img src="{% static 'Images/backgrounds/home2.png' %}" style="width:100%" />
  <div class="text">Caption Two</div>
</div>

<div class="mySlides">
  <div class="numbertext">3 / 4</div>
  <img src="{% static 'Images/backgrounds/home3.png' %}" style="width:100%" />
  <div class="text">Caption Three</div>
</div>

<div class="mySlides">
  <div class="numbertext">4 / 4</div>
      <img src="{% static 'Images/backgrounds/home4.png' %}" style="width:100%" />
  <div class="text">Caption Four</div>
</div>

<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
<a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
   <span class="dot" onclick="currentSlide(4)"></span> 
</div>

<p class="w3-center visit"><em>You have visited this page {{ num_visits }} {% if num_visits == 1 %} time {% else %} times{% endif %}.</em></p><br>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>

{% endblock %}

/** Thay images **/

main/templates/locations.html
{% extends "base_generic.html" %}
{% block title %}Location{% endblock %}
{% block content %}

<main class="w3-content w3-container w3-padding-64">
    <h2 class="w3-center"> RungMuaCafe Locations </h2>
    <p class="w3-center"><em> You can check our Branches</em></p><br>


    <div class="w3-row-padding w3-center">
        <div class="w3-col m8">

                <div id="map" style="width:100%; height:300px;"></div>
                <script type="text/javascript">
                    var map = L.map('map').setView([37.4080, 127.35], 9);
                    var osmLayer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                        maxZoom: 18,
                        attribution: 'Data, imagery and map information provided by <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors.'
                    });
                    map.addLayer(osmLayer);
                    var data = {
                      "type": "FeatureCollection",
                      "features": [
                        {% for obj in csv_list %}
                        {
                          "type": "Feature",
                          "properties": {
                            "full_name": "{{ obj.full_name }}",
                            "id": "{{ obj.id }}"
                          },
                          "geometry": {
                            "type": "Point",
                            "coordinates": [{{ obj.x }}, {{ obj.y }}]
                          }
                        }{% if not loop.last %},{% endif %}
                        {% endfor %}
                      ]
                    };
                    var dataLayer = L.geoJson(data, {
                        onEachFeature: function(feature, layer) {
                            layer.bindPopup(feature.properties.full_name);
                        }
                    });
                    map.addLayer(dataLayer);
                </script>
        </div>
        <div class="w3-col m4">
                <p></p>
                <p></p>
                <h5>5 branches</h5>
                </br>
                <p>서울시 강남구 테헤란로 385</p>
                <p>서울시 올림픽공원대로 293</p>
                <p>서울시 양평구 산림로 201</p>
                <p>서울시 석촌호수</p>
                <p>일산시 미아로 291</p>
        </div>


    </div>
</main>


{% endblock %}

main/templates/login.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="login">
    <h2>Sign In</h2>
    </br>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success btn-product" value="sign In" />
    </form>
</div>
{% endblock %}

main/templates/menu.html
{% extends 'base_generic.html' %}
{% block title %}Menu{% endblock %}
{% block content %}
<div class="container-fluid">
<iframe src="https://drive.google.com/file/d/1v4864qg3eTQe22pUgeBnCMz5ErP4UtwF/preview" width="100%" height="100%">This browser does not support PDFs. Please download the PDF to view it: Download PDF</iframe>
</div>
{% endblock %}

main/templates/offers.html
{% extends 'base_generic.html' %}
{% block title %}Offers{% endblock %}

{% load staticfiles %}
{% block content %}
<div class="w3-row-padding w3-center">
    <img class= "img-fluid"  src="{% static 'Images/backgrounds/offers1.png' %}">
</div>


{% endblock %}

main/templates/onlineShopping.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container">
    <h1>OnlineShopping</h1>
</div>
{% endblock %}